[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = true
  conditions = {Accept-Language = ["en*"], Language = ["en"]}

[[redirects]]
  from = "/"
  to = "/ru"
  status = 302
  force = true
  conditions = {Accept-Language = ["ru*"], Language = ["ru"]}

[[redirects]]
  from = "/"
  to = "/uk"
  status = 302
  force = true
  conditions = {Accept-Language = ["uk*"], Language = ["uk"]}

[[redirects]]
  from = "/"
  to = "/de"
  status = 302
  force = true
  conditions = {Accept-Language = ["de*"], Language = ["de"]}

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"