[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/ssr"
  status = 200
  force = true
